# Numpy Indexing and Selection

In [1]:
import numpy as np


In [4]:
arr = np.arange(0, 11)


In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [8]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
sorted(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
test = [i for i in range(11)]

In [14]:
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
test[0:5] = 100

TypeError: can only assign an iterable

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy[:] = 100

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])


In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]


5

In [30]:
arr_2d[1,2]

30

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [35]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [37]:
arr = np.arange(1, 11)

In [38]:
arr > 1

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
test > 1

TypeError: '>' not supported between instances of 'list' and 'int'

In [41]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [47]:
arr_2d[arr_2d > 30]

array([35, 40, 45])

In [51]:
new_2d = np.arange(50)
new_2d = new_2d.reshape(5, 10)

In [52]:
new_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])