# Numpy Arrays

In [1]:
my_list = [1,2,3]


In [2]:
my_list


[1, 2, 3]

In [4]:
import numpy as np
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
multi_arr = np.array(my_mat)

In [8]:
multi_arr[0]

array([1, 2, 3])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(1)

array([1.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(10)

array([0.8756417 , 0.748493  , 0.18245341, 0.6156262 , 0.78525085,
       0.8449756 , 0.9279164 , 0.23134252, 0.03023758, 0.65179997])

In [22]:
np.random.rand(10,10)

array([[0.33111491, 0.79257118, 0.95714235, 0.4676503 , 0.8551527 ,
        0.47763036, 0.22066864, 0.75529386, 0.65604346, 0.57930388],
       [0.42766968, 0.62455481, 0.49433066, 0.68235143, 0.99965571,
        0.23957676, 0.42102475, 0.92335463, 0.10717534, 0.2828447 ],
       [0.65001258, 0.40218977, 0.07624158, 0.00617287, 0.08334187,
        0.25536859, 0.33199634, 0.12160928, 0.03914442, 0.28014493],
       [0.8460047 , 0.85549036, 0.63776008, 0.04327302, 0.69489502,
        0.05639069, 0.00470659, 0.33509378, 0.15441785, 0.86696792],
       [0.69583917, 0.20190742, 0.91148761, 0.72860553, 0.86010406,
        0.94587362, 0.63635615, 0.10757109, 0.85651592, 0.21971024],
       [0.97727464, 0.3396006 , 0.20366848, 0.55646877, 0.91578651,
        0.39613384, 0.21569128, 0.54400814, 0.97518113, 0.3731367 ],
       [0.28281523, 0.57459594, 0.10099443, 0.92504925, 0.44386768,
        0.70256617, 0.02631324, 0.32440094, 0.72006837, 0.90596864],
       [0.05003862, 0.92208382, 0.0447196

In [24]:
np.random.randn(4,4)

array([[-1.03904892,  0.00358764,  0.13296189,  0.09748717],
       [-0.16169392, -0.88733258,  2.06143331,  0.63695925],
       [-0.54211292, -0.02280844,  0.84610848,  0.23280366],
       [-0.76573924, -0.1141886 ,  0.97535587, -0.53044665]])

In [63]:
np.random.randint(1, 100, 10)

array([55, 95, 44, 67, 71, 11, 25, 49, 76, 34])

In [64]:
arr = np.arange(25)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
randarr = np.random.randint(0,50,10)

In [67]:
randarr

array([ 8, 23,  9, 49, 48, 22, 37,  3, 33,  5])

In [68]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
randarr.min()


3

In [78]:
randarr.argmax()

3

In [79]:
randarr.argmin()

7

In [81]:
arr.shape


(25,)

In [ ]:
reshaped_arr =  arr.reshape